In [2]:
pip install matplotlib

Requirement already satisfied: matplotlib in /Users/kamelleeto/Documents/Datascientest/projet Rakuten/.venv/lib/python3.13/site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in /Users/kamelleeto/Documents/Datascientest/projet Rakuten/.venv/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/kamelleeto/Documents/Datascientest/projet Rakuten/.venv/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/kamelleeto/Documents/Datascientest/projet Rakuten/.venv/lib/python3.13/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/kamelleeto/Documents/Datascientest/projet Rakuten/.venv/lib/python3.13/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /Users/kamelleeto/Documents/Datascientest/projet Rakuten/.venv/lib/python3.13/site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/kamelleeto/Documents/Datascientest/projet Rakuten/.venv/lib/python3.13/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /Users/kamelleeto/Documents/Datascientest/projet Rakuten/.venv/lib/python3.13/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /Users/kamelleeto/Documents/Datascientest/projet Rakuten/.venv/lib/python3.13/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/kamelleeto/Documents/Datascientest/projet Rakuten/.venv/lib/python3.13/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/kamelleeto/Documents/Datascientest/projet Rakuten/.venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

df = pd.read_csv("../data/X_train_update.csv", index_col=0)
df.head()

,designation,description,productid,imageid
0,Olivia: Personalisiertes Notizbuch / 150 Seite...,NaN,3804725264,1263597046
1,Journal Des Arts (Le) N° 133 Du 28/09/2001 - L...,NaN,436067568,1008141237
2,Grand Stylet Ergonomique Bleu Gamepad Nintendo...,PILOT STYLE Touch Pen de marque Speedlink est ...,201115110,938777978
3,Peluche Donald - Europe - Disneyland 2000 (Mar...,NaN,50418756,457047496
4,La Guerre Des Tuques,Luc a des id&eacute;es de grandeur. Il veut or...,278535884,1077757786

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 84916 entries, 0 to 84915
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   designation  84916 non-null  str
 1   description  55116 non-null  str
 2   productid    84916 non-null  int64
 3   imageid      84916 non-null  int64
dtypes: int64(2), str(2)
memory usage: 2.6 MB

In [13]:
quality = pd.DataFrame({
    'dtype':       df.dtypes,
    'non_null':    df.notna().sum(),
    'null':        df.isna().sum(),
    'null_%':      (df.isna().mean() * 100).round(1),
    'n_unique':    df.nunique(),
})
quality

             dtype  non_null   null  null_%  n_unique
designation    str     84916      0     0.0     82265
description    str     55116  29800    35.1     47506
productid    int64     84916      0     0.0     84916
imageid      int64     84916      0     0.0     84916

In [8]:
df_y = pd.read_csv("../data/Y_train_CVw08PX.csv", index_col=0)
display(df_y.head())
print(df_y.nunique())

   prdtypecode
0           10
1         2280
2           50
3         1280
4         2705

prdtypecode    27
dtype: int64

In [9]:
df_y['prdtypecode'].value_counts().sort_values(ascending=False)

prdtypecode
2583    10209
1560     5073
1300     5045
2060     4993
2522     4989
1280     4870
2403     4774
2280     4760
1920     4303
1160     3953
1320     3241
10       3116
2705     2761
1140     2671
2582     2589
40       2508
2585     2496
1302     2491
1281     2070
50       1681
2462     1421
2905      872
60        832
2220      824
1301      807
1940      803
1180      764
Name: count, dtype: int64

In [ ]:

code_counts = df_y['prdtypecode'].value_counts()
print("Item counts per code:")
print(code_counts)


plt.figure(figsize=(12, 6))
plt.bar(code_counts.index, code_counts.values,color='skyblue', edgecolor='black')
plt.title('Distribution of Product Type Codes')
plt.xlabel('Product Type Code')
plt.ylabel('Number of Items')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)

Item counts per code:
prdtypecode
2583    10209
1560     5073
1300     5045
2060     4993
2522     4989
1280     4870
2403     4774
2280     4760
1920     4303
1160     3953
1320     3241
10       3116
2705     2761
1140     2671
2582     2589
40       2508
2585     2496
1302     2491
1281     2070
50       1681
2462     1421
2905      872
60        832
2220      824
1301      807
1940      803
1180      764
Name: count, dtype: int64

AttributeError: module 'matplotlib.pyplot' has no attribute 'barplot'